name: Presubmit checks
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

env:
  GO_VERSION: go1.24rc1

jobs:
  style:
    name: Code style check
    runs-on: ubuntu-latest
    steps:
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: {{ env.GO_VERSION }}

      - name: checkout
        uses: actions/checkout@v3

      - name: run lint
        run: make lint

      - name: run format check
        run: make check

  sdk-tests:
    name: SDK tests
    runs-on: ubuntu-latest
    steps:
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: {{ env.GO_VERSION }}

      - name: checkout
        uses: actions/checkout@v3

      - name: run tests
        run: make test

  examples:
    name: Examples Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
          key: examples-${{ hashFiles('**/go.mod', '**/go.sum') }}-{{ env.GO_VERSION }}

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: {{ env.GO_VERSION }}

      - name: Build examples
        run: make build.examples

      - name: Test examples
        run: make test.examples
